language: node_js
node_js:
- '8'
install:
- npm i
script:
- npm run generate
after_success:
- npm test
deploy:
  local-dir: dist
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  target-branch: master
  on:
    branch: deploy
