language: node_js
node_js:
- '8'
install:
- npm i
script:
- npm run generate
after_success:
- npm test
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: gh-pages
